#!/usr/bin/env python 

#Exercises 1 - Step 1.1 
import pandas as pd 

dataframe = pd.read_csv('/Users/cmdb/Desktop/backup data/Week1-HW/aau1043_dnm.csv')

# print(dataframe)

deNovoCount = {}
for i in range(len(dataframe)): 
	proband_id = dataframe.loc[i,'Proband_id']
	parent = dataframe.loc[i, 'Phase_combined']
	if proband_id not in deNovoCount: 
		deNovoCount[proband_id] = [0, 0]
	if parent == 'mother':
		deNovoCount[proband_id][0] += 1
	elif parent == 'father':
		deNovoCount[proband_id][1] += 1 
#print(deNovoCount)

#Step1.3 

deNovoCountDF = pd.DataFrame.from_dict(deNovoCount, orient = 'index', columns = ['maternal_dnm', 'paternal_dnm'])
# print(deNovoCountDF)

#Step1.4 

dataframe1= pd.read_csv('/Users/cmdb/Desktop/backup data/Week1-HW/aau1043_parental_age.csv', index_col = 0)
# print(dataframe1)

# #Step1.5 
dfCombined = pd.concat([deNovoCountDF, dataframe1], axis = 1, join = 'inner')
# print(dfCombined)


#Exercises 2 

#Step 2.1
import matplotlib.pyplot as plt 

# fig1, ax1 = plt.subplots()
# ax1.scatter(dfCombined["Mother_age"], dfCombined["maternal_dnm"], c = "red")
# ax1.set_xlabel("Mother Age(Year Old)")
# ax1.set_ylabel("Maternal Inherited de novo Mutations")
# ax1.set_title("Maternal Inherited de novo Mutations across Mother Ages")
# plt.show()
# fig1.savefig("ex2_a.png")



# fig2, ax2 = plt.subplots()
# ax2.scatter(dfCombined["Father_age"], dfCombined["paternal_dnm"], c = "blue")
# ax2.set_xlabel("Father Age(Year Old)")
# ax2.set_ylabel("Paternal Inherited de novo Mutations")
# ax2.set_title("Paternal Inherited de novo Mutations across Father Ages")
# plt.show()
# fig2.savefig("ex2_b.png")

#Step 2.2 
import scipy.stats as sps 
import statsmodels.formula.api as smf 
import statsmodels.api as sm 

# model = smf.ols(formula = "maternal_dnm ~ 1 + Mother_age", data = dfCombined)
# result_m = model.fit()
# print(result_m.summary())


model = smf.ols(formula = "paternal_dnm ~ 1 + Father_age", data = dfCombined)
result_p = model.fit()
print(result_p.summary())

